# Generated by Django 3.1.7 on 2021-03-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField(help_text='full url', unique=True)),
                ('url_hash', models.URLField(help_text='short url', unique=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'UrlInfo',
                'verbose_name_plural': 'UrlInfo',
                'db_table': 'urlinfo',
            },
        ),
    ]
